// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2JgLDaRXSyfIyQWKCrpSYwaqIWA5LUv0',
    appId: '1:813472636970:android:f17569373a9b269325e353',
    messagingSenderId: '813472636970',
    projectId: 'veto-be3f1',
    storageBucket: 'veto-be3f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaUQVTML88VZcmaWCxXKZ_18TDcVVa3zU',
    appId: '1:813472636970:ios:2c66aa60b48aedcb25e353',
    messagingSenderId: '813472636970',
    projectId: 'veto-be3f1',
    storageBucket: 'veto-be3f1.firebasestorage.app',
    iosBundleId: 'com.example.veto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaUQVTML88VZcmaWCxXKZ_18TDcVVa3zU',
    appId: '1:813472636970:ios:2c66aa60b48aedcb25e353',
    messagingSenderId: '813472636970',
    projectId: 'veto-be3f1',
    storageBucket: 'veto-be3f1.firebasestorage.app',
    iosBundleId: 'com.example.veto',
  );
}
